language: cpp
os: linux
dist: trusty
notifications:
  email: false
before_script:
- sudo apt-get install libboost-test-dev -y
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install g++-6 -y
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/source.list
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_filter_test_driven-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ualkud:$BINTRAY_KEY "https://api.bintray.com/content/alkud/ip_filter_test_driven/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter_test_driven-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publsih=1"
